# Generated by Django 4.1.13 on 2024-10-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Image', models.FileField(upload_to='media')),
                ('Name', models.CharField(max_length=40)),
                ('Role', models.CharField(max_length=40)),
            ],
        ),
    ]
